export enum SkillType {
    HTML = 'HTML',
    CSS = 'CSS',
    JAVASCRIPT = 'Javascript',
    GIT = 'Git',
    TYPESCRIPT = 'Typescript',
    SASS = 'SASS',
    ANGULAR = 'Angular',
    REACT = 'React',
    VUEJS = 'VueJs',
    NODEJS = 'NodeJs',
    MONGODB = 'MongoDB',
    MYSQL = 'MySQL',
    GOLANG = 'Golang',
    DOCKER = 'Docker',
    DIRECTUS = 'Directus',
    API = 'API',
    FIGMA = 'Figma',
    PHOTOSHOP = 'Photoshop',
    ILLUSTRATOR = 'Illustrator'
}