name: Build and Deploy Script
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20.12.2
    - name: Install Dependencies
      run: npm install
    - name: Build Angular App
      run: npm run build
    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
    - name: Deploy to gh pages
      run: |
        npx angular-cli-ghpages --dir=dist/portfolio_2_0_0 --no-silent
      env:
        CI: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}